// =====================================================
//  DATABASE — Expense Records + Category Config
//  Transactions: Oct 2025 – Mar 2026
// =====================================================

const CATEGORY_CONFIG = {
  'Food & Dining':       { icon: '🍜', color: '#e8845a', bg: 'rgba(232,132,90,0.12)'  },
  'Transportation':      { icon: '🚗', color: '#5a9fd4', bg: 'rgba(90,159,212,0.12)'  },
  'Shopping & Clothing': { icon: '👗', color: '#c870b0', bg: 'rgba(200,112,176,0.12)' },
  'Entertainment':       { icon: '🎬', color: '#9070d0', bg: 'rgba(144,112,208,0.12)' },
  'Healthcare':          { icon: '💊', color: '#e87070', bg: 'rgba(232,112,112,0.12)' },
  'Education':           { icon: '📚', color: '#5ab8a0', bg: 'rgba(90,184,160,0.12)'  },
  'Utilities':           { icon: '💡', color: '#f5b030', bg: 'rgba(245,176,48,0.12)'  },
  'Housing':             { icon: '🏠', color: '#a07840', bg: 'rgba(160,120,64,0.12)'  },
  'Travel':              { icon: '✈️', color: '#5080d0', bg: 'rgba(80,128,208,0.12)'  },
  'Personal Care':       { icon: '✨', color: '#d860a0', bg: 'rgba(216,96,160,0.12)'  },
  'Subscriptions':       { icon: '📱', color: '#7060c8', bg: 'rgba(112,96,200,0.12)'  },
  'Savings':             { icon: '💰', color: '#50a870', bg: 'rgba(80,168,112,0.12)'  },
  'Gifts & Donations':   { icon: '🎁', color: '#e05878', bg: 'rgba(224,88,120,0.12)'  },
  'Pet Care':            { icon: '🐱', color: '#d88030', bg: 'rgba(216,128,48,0.12)'  },
  'Home & Garden':       { icon: '🌿', color: '#60a858', bg: 'rgba(96,168,88,0.12)'   },
};

const EXPENSES = [
  // ===== OCTOBER 2025 =====
  { date:'2025-10-01', category:'Food & Dining',       sub:'Breakfast', desc:'Nasi Lemak at Warung Mak Cik',      amount:5.50,   person:'Sarah', payment:'Cash',           month:'Oct 2025' },
  { date:'2025-10-02', category:'Transportation',       sub:'Fuel',      desc:'Petrol at Shell Station',           amount:80.00,  person:'Alex',  payment:'Credit Card',    month:'Oct 2025' },
  { date:'2025-10-03', category:'Food & Dining',       sub:'Lunch',     desc:'Lunch at Mamak',                    amount:12.50,  person:'Sarah', payment:'Cash',           month:'Oct 2025' },
  { date:'2025-10-04', category:'Shopping & Clothing', sub:'Clothing',  desc:'H&M Summer Collection',             amount:189.90, person:'Sarah', payment:'Credit Card',    month:'Oct 2025' },
  { date:'2025-10-05', category:'Utilities',           sub:'Internet',  desc:'Unifi Monthly Subscription',        amount:89.00,  person:'Alex',  payment:'Auto Debit',     month:'Oct 2025' },
  { date:'2025-10-06', category:'Entertainment',       sub:'Movies',    desc:'Cinema Tickets x2',                 amount:38.00,  person:'Alex',  payment:'E-Wallet',       month:'Oct 2025' },
  { date:'2025-10-07', category:'Food & Dining',       sub:'Groceries', desc:'Weekly Groceries at Jaya Grocer',   amount:156.40, person:'Sarah', payment:'E-Wallet',       month:'Oct 2025' },
  { date:'2025-10-08', category:'Healthcare',          sub:'Pharmacy',  desc:'Cold Medicine at Guardian',         amount:45.60,  person:'Sarah', payment:'Cash',           month:'Oct 2025' },
  { date:'2025-10-09', category:'Transportation',       sub:'Grab',      desc:'Grab to KLCC',                      amount:22.00,  person:'Alex',  payment:'E-Wallet',       month:'Oct 2025' },
  { date:'2025-10-10', category:'Subscriptions',       sub:'Streaming', desc:'Netflix Monthly',                   amount:55.00,  person:'Alex',  payment:'Credit Card',    month:'Oct 2025' },
  { date:'2025-10-11', category:'Food & Dining',       sub:'Dinner',    desc:"Dinner at Chili's",                 amount:98.70,  person:'Sarah', payment:'Credit Card',    month:'Oct 2025' },
  { date:'2025-10-12', category:'Personal Care',       sub:'Haircare',  desc:'Shampoo & Conditioner',             amount:67.80,  person:'Sarah', payment:'Cash',           month:'Oct 2025' },
  { date:'2025-10-13', category:'Education',           sub:'Books',     desc:'Programming Book',                  amount:75.00,  person:'Alex',  payment:'Online Transfer', month:'Oct 2025' },
  { date:'2025-10-14', category:'Utilities',           sub:'Electric',  desc:'Electricity Bill',                  amount:220.50, person:'Alex',  payment:'Online Transfer', month:'Oct 2025' },
  { date:'2025-10-15', category:'Food & Dining',       sub:'Snacks',    desc:'Boba Tea & Snacks',                 amount:28.00,  person:'Sarah', payment:'E-Wallet',       month:'Oct 2025' },
  { date:'2025-10-16', category:'Travel',              sub:'Parking',   desc:'Monthly Parking Fee',               amount:150.00, person:'Alex',  payment:'Cash',           month:'Oct 2025' },
  { date:'2025-10-17', category:'Home & Garden',       sub:'Cleaning',  desc:'Cleaning Supplies',                 amount:43.20,  person:'Sarah', payment:'Cash',           month:'Oct 2025' },
  { date:'2025-10-18', category:'Gifts & Donations',   sub:'Gift',      desc:'Birthday Gift for Friend',          amount:120.00, person:'Sarah', payment:'Credit Card',    month:'Oct 2025' },
  { date:'2025-10-19', category:'Food & Dining',       sub:'Breakfast', desc:'McDonalds Breakfast',               amount:18.50,  person:'Alex',  payment:'E-Wallet',       month:'Oct 2025' },
  { date:'2025-10-20', category:'Transportation',       sub:'Toll',      desc:"Touch n' Go Reload",               amount:50.00,  person:'Alex',  payment:'E-Wallet',       month:'Oct 2025' },
  { date:'2025-10-21', category:'Subscriptions',       sub:'Music',     desc:'Spotify Premium',                   amount:17.00,  person:'Sarah', payment:'Credit Card',    month:'Oct 2025' },
  { date:'2025-10-22', category:'Healthcare',          sub:'Dental',    desc:'Dental Check-up',                   amount:180.00, person:'Alex',  payment:'Credit Card',    month:'Oct 2025' },
  { date:'2025-10-23', category:'Food & Dining',       sub:'Lunch',     desc:'Korean BBQ Lunch',                  amount:85.00,  person:'Sarah', payment:'Credit Card',    month:'Oct 2025' },
  { date:'2025-10-24', category:'Personal Care',       sub:'Skincare',  desc:'SK-II Toner',                       amount:299.00, person:'Sarah', payment:'Credit Card',    month:'Oct 2025' },
  { date:'2025-10-25', category:'Savings',             sub:'E-Fund',    desc:'Monthly Savings Transfer',          amount:500.00, person:'Alex',  payment:'Bank Transfer',  month:'Oct 2025' },
  { date:'2025-10-26', category:'Food & Dining',       sub:'Dinner',    desc:'Steamboat with Family',             amount:210.00, person:'Alex',  payment:'Credit Card',    month:'Oct 2025' },
  { date:'2025-10-27', category:'Shopping & Clothing', sub:'Electronics', desc:'Phone Case & Screen Protector',   amount:65.00,  person:'Alex',  payment:'E-Wallet',       month:'Oct 2025' },
  { date:'2025-10-28', category:'Pet Care',            sub:'Food',      desc:'Cat Food (2 bags)',                 amount:89.00,  person:'Sarah', payment:'E-Wallet',       month:'Oct 2025' },
  { date:'2025-10-29', category:'Utilities',           sub:'Water',     desc:'Water Bill',                        amount:35.80,  person:'Alex',  payment:'Online Transfer', month:'Oct 2025' },
  { date:'2025-10-30', category:'Entertainment',       sub:'Games',     desc:'Steam Game Purchase',               amount:59.00,  person:'Alex',  payment:'Credit Card',    month:'Oct 2025' },
  { date:'2025-10-31', category:'Food & Dining',       sub:'Groceries', desc:'Monthly Stock-up at AEON',          amount:287.60, person:'Sarah', payment:'Credit Card',    month:'Oct 2025' },

  // ===== NOVEMBER 2025 =====
  { date:'2025-11-01', category:'Food & Dining',       sub:'Breakfast', desc:"Roti Canai & Teh Tarik",            amount:7.50,   person:'Alex',  payment:'Cash',           month:'Nov 2025' },
  { date:'2025-11-02', category:'Transportation',       sub:'Fuel',      desc:'Petrol at BHPetrol',               amount:75.00,  person:'Alex',  payment:'Credit Card',    month:'Nov 2025' },
  { date:'2025-11-03', category:'Healthcare',          sub:'Clinic',    desc:'Doctor Visit (Fever)',               amount:80.00,  person:'Sarah', payment:'Cash',           month:'Nov 2025' },
  { date:'2025-11-04', category:'Food & Dining',       sub:'Lunch',     desc:'Sushi Lunch at Sushi King',         amount:95.00,  person:'Sarah', payment:'Credit Card',    month:'Nov 2025' },
  { date:'2025-11-05', category:'Utilities',           sub:'Internet',  desc:'Unifi Monthly Subscription',        amount:89.00,  person:'Alex',  payment:'Auto Debit',     month:'Nov 2025' },
  { date:'2025-11-06', category:'Shopping & Clothing', sub:'Clothing',  desc:'Uniqlo Hoodie',                     amount:199.00, person:'Alex',  payment:'Credit Card',    month:'Nov 2025' },
  { date:'2025-11-07', category:'Entertainment',       sub:'Karaoke',   desc:'Karaoke Night',                     amount:75.00,  person:'Sarah', payment:'Cash',           month:'Nov 2025' },
  { date:'2025-11-08', category:'Food & Dining',       sub:'Groceries', desc:'Pasar Malam Shopping',              amount:88.50,  person:'Sarah', payment:'Cash',           month:'Nov 2025' },
  { date:'2025-11-09', category:'Transportation',       sub:'Grab',      desc:'Grab to Airport',                   amount:55.00,  person:'Alex',  payment:'E-Wallet',       month:'Nov 2025' },
  { date:'2025-11-10', category:'Subscriptions',       sub:'Streaming', desc:'Netflix Monthly',                   amount:55.00,  person:'Alex',  payment:'Credit Card',    month:'Nov 2025' },
  { date:'2025-11-11', category:'Education',           sub:'Course',    desc:'Udemy Course (Discount)',            amount:45.99,  person:'Alex',  payment:'Credit Card',    month:'Nov 2025' },
  { date:'2025-11-12', category:'Food & Dining',       sub:'Dinner',    desc:'Pizza Night',                       amount:65.00,  person:'Sarah', payment:'E-Wallet',       month:'Nov 2025' },
  { date:'2025-11-13', category:'Personal Care',       sub:'Grooming',  desc:'Haircut at Saloon',                 amount:50.00,  person:'Alex',  payment:'Cash',           month:'Nov 2025' },
  { date:'2025-11-14', category:'Utilities',           sub:'Electric',  desc:'Electricity Bill',                  amount:198.30, person:'Alex',  payment:'Online Transfer', month:'Nov 2025' },
  { date:'2025-11-15', category:'Travel',              sub:'Trip',      desc:'Weekend Trip to Penang (Hotel)',    amount:380.00, person:'Sarah', payment:'Credit Card',    month:'Nov 2025' },
  { date:'2025-11-16', category:'Travel',              sub:'Trip',      desc:'Penang Food Trail',                 amount:145.00, person:'Sarah', payment:'Cash',           month:'Nov 2025' },
  { date:'2025-11-17', category:'Home & Garden',       sub:'Furniture', desc:'Small Shelf from IKEA',             amount:159.00, person:'Sarah', payment:'Credit Card',    month:'Nov 2025' },
  { date:'2025-11-18', category:'Food & Dining',       sub:'Breakfast', desc:'Old Town White Coffee',             amount:22.00,  person:'Alex',  payment:'E-Wallet',       month:'Nov 2025' },
  { date:'2025-11-19', category:'Transportation',       sub:'Toll',      desc:"Touch n' Go Reload",               amount:100.00, person:'Alex',  payment:'E-Wallet',       month:'Nov 2025' },
  { date:'2025-11-20', category:'Subscriptions',       sub:'Music',     desc:'Spotify Premium',                   amount:17.00,  person:'Sarah', payment:'Credit Card',    month:'Nov 2025' },
  { date:'2025-11-21', category:'Gifts & Donations',   sub:'Donation',  desc:'Charity Donation',                  amount:50.00,  person:'Sarah', payment:'Online Transfer', month:'Nov 2025' },
  { date:'2025-11-22', category:'Food & Dining',       sub:'Lunch',     desc:'Thai Food Lunch',                   amount:42.00,  person:'Alex',  payment:'Cash',           month:'Nov 2025' },
  { date:'2025-11-23', category:'Pet Care',            sub:'Vet',       desc:'Cat Vaccination',                   amount:150.00, person:'Sarah', payment:'Credit Card',    month:'Nov 2025' },
  { date:'2025-11-24', category:'Savings',             sub:'E-Fund',    desc:'Monthly Savings Transfer',          amount:500.00, person:'Alex',  payment:'Bank Transfer',  month:'Nov 2025' },
  { date:'2025-11-25', category:'Shopping & Clothing', sub:'Accessories', desc:'Sunglasses',                      amount:179.00, person:'Sarah', payment:'Credit Card',    month:'Nov 2025' },
  { date:'2025-11-26', category:'Food & Dining',       sub:'Dinner',    desc:'Family Dinner',                     amount:320.00, person:'Alex',  payment:'Credit Card',    month:'Nov 2025' },
  { date:'2025-11-27', category:'Healthcare',          sub:'Pharmacy',  desc:'Vitamins & Supplements',            amount:88.00,  person:'Alex',  payment:'Cash',           month:'Nov 2025' },
  { date:'2025-11-28', category:'Entertainment',       sub:'Theme Park', desc:'Sunway Lagoon Tickets',            amount:180.00, person:'Sarah', payment:'Credit Card',    month:'Nov 2025' },
  { date:'2025-11-29', category:'Utilities',           sub:'Water',     desc:'Water Bill',                        amount:38.20,  person:'Alex',  payment:'Online Transfer', month:'Nov 2025' },
  { date:'2025-11-30', category:'Food & Dining',       sub:'Groceries', desc:'Monthly Stock-up at Lotus',         amount:310.80, person:'Sarah', payment:'Credit Card',    month:'Nov 2025' },

  // ===== DECEMBER 2025 =====
  { date:'2025-12-01', category:'Food & Dining',       sub:'Breakfast', desc:'Dim Sum Sunday',                    amount:65.00,  person:'Sarah', payment:'Cash',           month:'Dec 2025' },
  { date:'2025-12-02', category:'Transportation',       sub:'Fuel',      desc:'Petrol at Petronas',               amount:85.00,  person:'Alex',  payment:'Credit Card',    month:'Dec 2025' },
  { date:'2025-12-03', category:'Shopping & Clothing', sub:'Sale',      desc:'Year End Sale at Pavilion',         amount:550.00, person:'Sarah', payment:'Credit Card',    month:'Dec 2025' },
  { date:'2025-12-04', category:'Entertainment',       sub:'Movies',    desc:'Avatar Sequel Cinema',              amount:45.00,  person:'Alex',  payment:'E-Wallet',       month:'Dec 2025' },
  { date:'2025-12-05', category:'Utilities',           sub:'Internet',  desc:'Unifi Monthly Subscription',        amount:89.00,  person:'Alex',  payment:'Auto Debit',     month:'Dec 2025' },
  { date:'2025-12-06', category:'Food & Dining',       sub:'Lunch',     desc:'Christmas Lunch',                   amount:125.00, person:'Sarah', payment:'Credit Card',    month:'Dec 2025' },
  { date:'2025-12-07', category:'Gifts & Donations',   sub:'Gifts',     desc:'Christmas Gifts',                   amount:450.00, person:'Sarah', payment:'Credit Card',    month:'Dec 2025' },
  { date:'2025-12-08', category:'Food & Dining',       sub:'Groceries', desc:'Christmas Week Groceries',          amount:220.00, person:'Sarah', payment:'E-Wallet',       month:'Dec 2025' },
  { date:'2025-12-09', category:'Healthcare',          sub:'Clinic',    desc:'Annual Health Check-up',            amount:350.00, person:'Alex',  payment:'Credit Card',    month:'Dec 2025' },
  { date:'2025-12-10', category:'Subscriptions',       sub:'Streaming', desc:'Netflix Monthly',                   amount:55.00,  person:'Alex',  payment:'Credit Card',    month:'Dec 2025' },
  { date:'2025-12-11', category:'Travel',              sub:'Trip',      desc:'Christmas Trip to Langkawi',        amount:1200.00,person:'Alex',  payment:'Credit Card',    month:'Dec 2025' },
  { date:'2025-12-12', category:'Personal Care',       sub:'Skincare',  desc:'Year-end Skincare Haul',            amount:420.00, person:'Sarah', payment:'Credit Card',    month:'Dec 2025' },
  { date:'2025-12-13', category:'Transportation',       sub:'Grab',      desc:'Grab during Holiday',               amount:88.00,  person:'Alex',  payment:'E-Wallet',       month:'Dec 2025' },
  { date:'2025-12-14', category:'Utilities',           sub:'Electric',  desc:'Electricity Bill (High Season)',    amount:285.60, person:'Alex',  payment:'Online Transfer', month:'Dec 2025' },
  { date:'2025-12-15', category:'Education',           sub:'Books',     desc:'New Year Planner & Journals',       amount:55.00,  person:'Sarah', payment:'E-Wallet',       month:'Dec 2025' },
  { date:'2025-12-16', category:'Food & Dining',       sub:'Dinner',    desc:'New Year Eve Dinner',               amount:320.00, person:'Sarah', payment:'Credit Card',    month:'Dec 2025' },
  { date:'2025-12-17', category:'Home & Garden',       sub:'Decoration', desc:'Christmas Decorations',            amount:189.00, person:'Sarah', payment:'Credit Card',    month:'Dec 2025' },
  { date:'2025-12-18', category:'Subscriptions',       sub:'Music',     desc:'Spotify Premium',                   amount:17.00,  person:'Sarah', payment:'Credit Card',    month:'Dec 2025' },
  { date:'2025-12-19', category:'Pet Care',            sub:'Food',      desc:'Premium Cat Food (Holiday Pack)',   amount:125.00, person:'Sarah', payment:'E-Wallet',       month:'Dec 2025' },
  { date:'2025-12-20', category:'Savings',             sub:'E-Fund',    desc:'Monthly Savings Transfer',          amount:500.00, person:'Alex',  payment:'Bank Transfer',  month:'Dec 2025' },
  { date:'2025-12-21', category:'Food & Dining',       sub:'Groceries', desc:'New Year Party Food',               amount:178.90, person:'Sarah', payment:'Credit Card',    month:'Dec 2025' },
  { date:'2025-12-22', category:'Transportation',       sub:'Toll',      desc:"Touch n' Go Reload",               amount:100.00, person:'Alex',  payment:'E-Wallet',       month:'Dec 2025' },
  { date:'2025-12-23', category:'Shopping & Clothing', sub:'Electronics', desc:'Year End Tech Deals',             amount:899.00, person:'Alex',  payment:'Credit Card',    month:'Dec 2025' },
  { date:'2025-12-24', category:'Entertainment',       sub:'Party',     desc:'New Year Celebration',              amount:250.00, person:'Alex',  payment:'Credit Card',    month:'Dec 2025' },
  { date:'2025-12-25', category:'Food & Dining',       sub:'Breakfast', desc:'Hotel Buffet Breakfast',            amount:98.00,  person:'Alex',  payment:'Credit Card',    month:'Dec 2025' },
  { date:'2025-12-26', category:'Utilities',           sub:'Water',     desc:'Water Bill',                        amount:40.50,  person:'Alex',  payment:'Online Transfer', month:'Dec 2025' },
  { date:'2025-12-27', category:'Food & Dining',       sub:'Snacks',    desc:'Festive Snacks & Cookies',          amount:88.50,  person:'Sarah', payment:'Cash',           month:'Dec 2025' },
  { date:'2025-12-28', category:'Personal Care',       sub:'Haircare',  desc:'Year-end Haircut & Treatment',      amount:180.00, person:'Sarah', payment:'Credit Card',    month:'Dec 2025' },
  { date:'2025-12-29', category:'Healthcare',          sub:'Pharmacy',  desc:'Year-end Medicine Stock',           amount:67.00,  person:'Alex',  payment:'Cash',           month:'Dec 2025' },
  { date:'2025-12-30', category:'Gifts & Donations',   sub:'Donation',  desc:'Year-end Charity',                  amount:100.00, person:'Sarah', payment:'Online Transfer', month:'Dec 2025' },
  { date:'2025-12-31', category:'Food & Dining',       sub:'Dinner',    desc:'New Year Countdown Dinner',         amount:280.00, person:'Alex',  payment:'Credit Card',    month:'Dec 2025' },

  // ===== JANUARY 2026 =====
  { date:'2026-01-01', category:'Food & Dining',       sub:'Breakfast', desc:'New Year Brunch',                   amount:85.00,  person:'Sarah', payment:'Credit Card',    month:'Jan 2026' },
  { date:'2026-01-02', category:'Transportation',       sub:'Fuel',      desc:'First Petrol of Year',              amount:80.00,  person:'Alex',  payment:'Credit Card',    month:'Jan 2026' },
  { date:'2026-01-03', category:'Housing',             sub:'Utilities', desc:'Electricity Bill',                  amount:210.00, person:'Alex',  payment:'Online Transfer', month:'Jan 2026' },
  { date:'2026-01-04', category:'Education',           sub:'Course',    desc:'New Year Learning - Coursera',      amount:199.00, person:'Alex',  payment:'Credit Card',    month:'Jan 2026' },
  { date:'2026-01-05', category:'Food & Dining',       sub:'Groceries', desc:'Weekly Groceries',                  amount:165.40, person:'Sarah', payment:'E-Wallet',       month:'Jan 2026' },
  { date:'2026-01-06', category:'Subscriptions',       sub:'Streaming', desc:'Netflix Monthly',                   amount:55.00,  person:'Alex',  payment:'Credit Card',    month:'Jan 2026' },
  { date:'2026-01-07', category:'Shopping & Clothing', sub:'Clothing',  desc:'Chinese New Year Outfit',           amount:380.00, person:'Sarah', payment:'Credit Card',    month:'Jan 2026' },
  { date:'2026-01-08', category:'Transportation',       sub:'Grab',      desc:'Grab to Office',                    amount:25.00,  person:'Alex',  payment:'E-Wallet',       month:'Jan 2026' },
  { date:'2026-01-09', category:'Food & Dining',       sub:'Lunch',     desc:'Lunch with Colleagues',             amount:55.00,  person:'Alex',  payment:'Cash',           month:'Jan 2026' },
  { date:'2026-01-10', category:'Healthcare',          sub:'Pharmacy',  desc:'Regular Supplements',               amount:98.00,  person:'Alex',  payment:'Cash',           month:'Jan 2026' },
  { date:'2026-01-11', category:'Entertainment',       sub:'Movies',    desc:'Movie Night',                       amount:38.00,  person:'Sarah', payment:'E-Wallet',       month:'Jan 2026' },
  { date:'2026-01-12', category:'Utilities',           sub:'Internet',  desc:'Unifi Monthly Subscription',        amount:89.00,  person:'Alex',  payment:'Auto Debit',     month:'Jan 2026' },
  { date:'2026-01-13', category:'Personal Care',       sub:'Skincare',  desc:'Moisturizer & Sunscreen',           amount:185.00, person:'Sarah', payment:'Credit Card',    month:'Jan 2026' },
  { date:'2026-01-14', category:'Food & Dining',       sub:'Dinner',    desc:'Restaurant Dinner',                 amount:120.00, person:'Sarah', payment:'Credit Card',    month:'Jan 2026' },
  { date:'2026-01-15', category:'Savings',             sub:'E-Fund',    desc:'Monthly Savings Transfer',          amount:500.00, person:'Alex',  payment:'Bank Transfer',  month:'Jan 2026' },
  { date:'2026-01-16', category:'Gifts & Donations',   sub:'Gift',      desc:'CNY Angpau Preparation',            amount:300.00, person:'Alex',  payment:'Cash',           month:'Jan 2026' },
  { date:'2026-01-17', category:'Transportation',       sub:'Toll',      desc:"Touch n' Go Reload",               amount:80.00,  person:'Alex',  payment:'E-Wallet',       month:'Jan 2026' },
  { date:'2026-01-18', category:'Home & Garden',       sub:'Cleaning',  desc:'CNY Spring Cleaning Supplies',      amount:125.00, person:'Sarah', payment:'Cash',           month:'Jan 2026' },
  { date:'2026-01-19', category:'Food & Dining',       sub:'Groceries', desc:'CNY Biscuits & Snacks',             amount:210.00, person:'Sarah', payment:'Credit Card',    month:'Jan 2026' },
  { date:'2026-01-20', category:'Pet Care',            sub:'Accessories', desc:'Cat Toys & Accessories',          amount:78.00,  person:'Sarah', payment:'E-Wallet',       month:'Jan 2026' },
  { date:'2026-01-21', category:'Subscriptions',       sub:'Music',     desc:'Spotify Premium',                   amount:17.00,  person:'Sarah', payment:'Credit Card',    month:'Jan 2026' },
  { date:'2026-01-22', category:'Entertainment',       sub:'Theme Park', desc:'CNY Family Activity',              amount:220.00, person:'Alex',  payment:'Credit Card',    month:'Jan 2026' },
  { date:'2026-01-23', category:'Food & Dining',       sub:'Reunion',   desc:'CNY Reunion Dinner',                amount:450.00, person:'Alex',  payment:'Credit Card',    month:'Jan 2026' },
  { date:'2026-01-24', category:'Utilities',           sub:'Water',     desc:'Water Bill',                        amount:33.60,  person:'Alex',  payment:'Online Transfer', month:'Jan 2026' },
  { date:'2026-01-25', category:'Shopping & Clothing', sub:'Home Goods', desc:'New Year Home Decor',              amount:255.00, person:'Sarah', payment:'Credit Card',    month:'Jan 2026' },
  { date:'2026-01-26', category:'Healthcare',          sub:'Clinic',    desc:'Flu Season Check-up',               amount:80.00,  person:'Sarah', payment:'Cash',           month:'Jan 2026' },
  { date:'2026-01-27', category:'Food & Dining',       sub:'Breakfast', desc:'CNY Open House Prep',               amount:88.00,  person:'Sarah', payment:'Cash',           month:'Jan 2026' },
  { date:'2026-01-28', category:'Travel',              sub:'Trip',      desc:'CNY Trip Back to Hometown',         amount:320.00, person:'Alex',  payment:'Credit Card',    month:'Jan 2026' },
  { date:'2026-01-29', category:'Education',           sub:'Books',     desc:'Investment Books',                  amount:95.00,  person:'Alex',  payment:'E-Wallet',       month:'Jan 2026' },
  { date:'2026-01-30', category:'Personal Care',       sub:'Grooming',  desc:'Haircut Before CNY',                amount:60.00,  person:'Alex',  payment:'Cash',           month:'Jan 2026' },
  { date:'2026-01-31', category:'Food & Dining',       sub:'Groceries', desc:'End of Month Groceries',            amount:145.30, person:'Sarah', payment:'E-Wallet',       month:'Jan 2026' },

  // ===== FEBRUARY 2026 =====
  { date:'2026-02-01', category:'Food & Dining',       sub:'Breakfast', desc:"Valentine's Day Brunch Prep",       amount:45.00,  person:'Sarah', payment:'Cash',           month:'Feb 2026' },
  { date:'2026-02-02', category:'Transportation',       sub:'Fuel',      desc:'Petrol',                            amount:78.00,  person:'Alex',  payment:'Credit Card',    month:'Feb 2026' },
  { date:'2026-02-03', category:'Healthcare',          sub:'Pharmacy',  desc:'Allergy Medicine',                  amount:65.00,  person:'Sarah', payment:'Cash',           month:'Feb 2026' },
  { date:'2026-02-04', category:'Food & Dining',       sub:'Groceries', desc:'Weekly Groceries',                  amount:172.60, person:'Sarah', payment:'E-Wallet',       month:'Feb 2026' },
  { date:'2026-02-05', category:'Utilities',           sub:'Internet',  desc:'Unifi Monthly Subscription',        amount:89.00,  person:'Alex',  payment:'Auto Debit',     month:'Feb 2026' },
  { date:'2026-02-06', category:'Shopping & Clothing', sub:'Gift',      desc:"Valentine's Gifts",                 amount:350.00, person:'Alex',  payment:'Credit Card',    month:'Feb 2026' },
  { date:'2026-02-07', category:'Entertainment',       sub:'Movies',    desc:"Valentine's Movie",                 amount:48.00,  person:'Alex',  payment:'E-Wallet',       month:'Feb 2026' },
  { date:'2026-02-08', category:'Food & Dining',       sub:'Dinner',    desc:"Valentine's Dinner (Fine Dining)",  amount:580.00, person:'Alex',  payment:'Credit Card',    month:'Feb 2026' },
  { date:'2026-02-09', category:'Personal Care',       sub:'Spa',       desc:'Valentine Couple Spa',              amount:480.00, person:'Sarah', payment:'Credit Card',    month:'Feb 2026' },
  { date:'2026-02-10', category:'Subscriptions',       sub:'Streaming', desc:'Netflix Monthly',                   amount:55.00,  person:'Alex',  payment:'Credit Card',    month:'Feb 2026' },
  { date:'2026-02-11', category:'Education',           sub:'Course',    desc:'Data Science Course',               amount:259.00, person:'Alex',  payment:'Credit Card',    month:'Feb 2026' },
  { date:'2026-02-12', category:'Transportation',       sub:'Grab',      desc:'Grab Weekend',                      amount:35.00,  person:'Sarah', payment:'E-Wallet',       month:'Feb 2026' },
  { date:'2026-02-13', category:'Food & Dining',       sub:'Lunch',     desc:'Japanese Lunch',                    amount:75.00,  person:'Sarah', payment:'Credit Card',    month:'Feb 2026' },
  { date:'2026-02-14', category:'Housing',             sub:'Utilities', desc:'Electricity Bill',                  amount:195.80, person:'Alex',  payment:'Online Transfer', month:'Feb 2026' },
  { date:'2026-02-15', category:'Savings',             sub:'E-Fund',    desc:'Monthly Savings Transfer',          amount:500.00, person:'Alex',  payment:'Bank Transfer',  month:'Feb 2026' },
  { date:'2026-02-16', category:'Food & Dining',       sub:'Snacks',    desc:'Cafe Hopping',                      amount:68.00,  person:'Sarah', payment:'E-Wallet',       month:'Feb 2026' },
  { date:'2026-02-17', category:'Transportation',       sub:'Toll',      desc:"Touch n' Go Reload",               amount:80.00,  person:'Alex',  payment:'E-Wallet',       month:'Feb 2026' },
  { date:'2026-02-18', category:'Home & Garden',       sub:'Plants',    desc:'Indoor Plants',                     amount:155.00, person:'Sarah', payment:'Cash',           month:'Feb 2026' },
  { date:'2026-02-19', category:'Subscriptions',       sub:'Music',     desc:'Spotify Premium',                   amount:17.00,  person:'Sarah', payment:'Credit Card',    month:'Feb 2026' },
  { date:'2026-02-20', category:'Pet Care',            sub:'Food',      desc:'Cat Food Monthly',                  amount:89.00,  person:'Sarah', payment:'E-Wallet',       month:'Feb 2026' },
  { date:'2026-02-21', category:'Food & Dining',       sub:'Groceries', desc:'Supermarket Run',                   amount:198.40, person:'Sarah', payment:'Credit Card',    month:'Feb 2026' },
  { date:'2026-02-22', category:'Healthcare',          sub:'Dental',    desc:'Teeth Whitening',                   amount:350.00, person:'Sarah', payment:'Credit Card',    month:'Feb 2026' },
  { date:'2026-02-23', category:'Entertainment',       sub:'Concert',   desc:'Concert Tickets',                   amount:280.00, person:'Sarah', payment:'Credit Card',    month:'Feb 2026' },
  { date:'2026-02-24', category:'Shopping & Clothing', sub:'Electronics', desc:'Wireless Earbuds',                amount:399.00, person:'Alex',  payment:'Credit Card',    month:'Feb 2026' },
  { date:'2026-02-25', category:'Gifts & Donations',   sub:'Gift',      desc:"Friend's Baby Shower Gift",         amount:150.00, person:'Sarah', payment:'Online Transfer', month:'Feb 2026' },
  { date:'2026-02-26', category:'Utilities',           sub:'Water',     desc:'Water Bill',                        amount:36.40,  person:'Alex',  payment:'Online Transfer', month:'Feb 2026' },
  { date:'2026-02-27', category:'Food & Dining',       sub:'Breakfast', desc:'Weekend Brunch',                    amount:95.00,  person:'Alex',  payment:'Credit Card',    month:'Feb 2026' },
  { date:'2026-02-28', category:'Personal Care',       sub:'Haircare',  desc:'Hair Coloring at Salon',            amount:280.00, person:'Sarah', payment:'Credit Card',    month:'Feb 2026' },

  // ===== MARCH 2026 =====
  { date:'2026-03-01', category:'Food & Dining',       sub:'Breakfast', desc:'Morning Coffee & Toast',            amount:15.00,  person:'Alex',  payment:'Cash',           month:'Mar 2026' },
  { date:'2026-03-02', category:'Transportation',       sub:'Fuel',      desc:'Petrol',                            amount:82.00,  person:'Alex',  payment:'Credit Card',    month:'Mar 2026' },
  { date:'2026-03-03', category:'Shopping & Clothing', sub:'Clothing',  desc:'New Work Attire',                   amount:420.00, person:'Alex',  payment:'Credit Card',    month:'Mar 2026' },
  { date:'2026-03-04', category:'Healthcare',          sub:'Clinic',    desc:'Medical Check-up',                  amount:150.00, person:'Alex',  payment:'Credit Card',    month:'Mar 2026' },
  { date:'2026-03-05', category:'Utilities',           sub:'Internet',  desc:'Unifi Monthly Subscription',        amount:89.00,  person:'Alex',  payment:'Auto Debit',     month:'Mar 2026' },
  { date:'2026-03-06', category:'Food & Dining',       sub:'Groceries', desc:'Weekly Groceries at Giant',         amount:155.80, person:'Sarah', payment:'E-Wallet',       month:'Mar 2026' },
  { date:'2026-03-07', category:'Entertainment',       sub:'Event',     desc:'Stand-up Comedy Show',              amount:120.00, person:'Sarah', payment:'Credit Card',    month:'Mar 2026' },
  { date:'2026-03-08', category:'Subscriptions',       sub:'Streaming', desc:'Netflix Monthly',                   amount:55.00,  person:'Alex',  payment:'Credit Card',    month:'Mar 2026' },
  { date:'2026-03-09', category:'Personal Care',       sub:'Skincare',  desc:'New Skincare Routine Set',          amount:365.00, person:'Sarah', payment:'Credit Card',    month:'Mar 2026' },
  { date:'2026-03-10', category:'Education',           sub:'Workshop',  desc:'Marketing Workshop',                amount:350.00, person:'Alex',  payment:'Online Transfer', month:'Mar 2026' },
  { date:'2026-03-11', category:'Food & Dining',       sub:'Lunch',     desc:'Lunch with Manager',                amount:88.00,  person:'Alex',  payment:'Cash',           month:'Mar 2026' },
  { date:'2026-03-12', category:'Transportation',       sub:'Grab',      desc:'Grab to Meeting',                   amount:30.00,  person:'Alex',  payment:'E-Wallet',       month:'Mar 2026' },
  { date:'2026-03-13', category:'Housing',             sub:'Utilities', desc:'Electricity Bill',                  amount:205.00, person:'Alex',  payment:'Online Transfer', month:'Mar 2026' },
  { date:'2026-03-14', category:'Home & Garden',       sub:'Appliance', desc:'Air Purifier',                      amount:599.00, person:'Sarah', payment:'Credit Card',    month:'Mar 2026' },
  { date:'2026-03-15', category:'Savings',             sub:'E-Fund',    desc:'Monthly Savings Transfer',          amount:500.00, person:'Alex',  payment:'Bank Transfer',  month:'Mar 2026' },
  { date:'2026-03-16', category:'Food & Dining',       sub:'Dinner',    desc:'Seafood Dinner',                    amount:245.00, person:'Sarah', payment:'Credit Card',    month:'Mar 2026' },
  { date:'2026-03-17', category:'Subscriptions',       sub:'Music',     desc:'Spotify Premium',                   amount:17.00,  person:'Sarah', payment:'Credit Card',    month:'Mar 2026' },
  { date:'2026-03-18', category:'Gifts & Donations',   sub:'Donation',  desc:'NGO Donation',                      amount:100.00, person:'Alex',  payment:'Online Transfer', month:'Mar 2026' },
  { date:'2026-03-19', category:'Pet Care',            sub:'Vet',       desc:'Annual Cat Health Check',           amount:220.00, person:'Sarah', payment:'Credit Card',    month:'Mar 2026' },
  { date:'2026-03-20', category:'Transportation',       sub:'Toll',      desc:"Touch n' Go Reload",               amount:100.00, person:'Alex',  payment:'E-Wallet',       month:'Mar 2026' },
  { date:'2026-03-21', category:'Food & Dining',       sub:'Groceries', desc:'Mid-month Groceries',               amount:188.90, person:'Sarah', payment:'E-Wallet',       month:'Mar 2026' },
  { date:'2026-03-22', category:'Shopping & Clothing', sub:'Accessories', desc:'Watch Battery & Strap',           amount:85.00,  person:'Alex',  payment:'Cash',           month:'Mar 2026' },
  { date:'2026-03-23', category:'Healthcare',          sub:'Pharmacy',  desc:'Vitamins Restock',                  amount:75.00,  person:'Alex',  payment:'Cash',           month:'Mar 2026' },
  { date:'2026-03-24', category:'Entertainment',       sub:'Museum',    desc:'Weekend Museum Visit',              amount:45.00,  person:'Sarah', payment:'E-Wallet',       month:'Mar 2026' },
  { date:'2026-03-25', category:'Food & Dining',       sub:'Breakfast', desc:'Breakfast Buffet at Hotel',         amount:120.00, person:'Sarah', payment:'Credit Card',    month:'Mar 2026' },
  { date:'2026-03-26', category:'Utilities',           sub:'Water',     desc:'Water Bill',                        amount:35.00,  person:'Alex',  payment:'Online Transfer', month:'Mar 2026' },
  { date:'2026-03-27', category:'Personal Care',       sub:'Grooming',  desc:'Haircut',                           amount:50.00,  person:'Alex',  payment:'Cash',           month:'Mar 2026' },
  { date:'2026-03-28', category:'Travel',              sub:'Road Trip', desc:'Road Trip to Cameron Highlands',    amount:680.00, person:'Alex',  payment:'Credit Card',    month:'Mar 2026' },
  { date:'2026-03-29', category:'Food & Dining',       sub:'Snacks',    desc:'Afternoon Tea',                     amount:55.00,  person:'Sarah', payment:'E-Wallet',       month:'Mar 2026' },
  { date:'2026-03-30', category:'Home & Garden',       sub:'Cleaning',  desc:'Monthly Cleaning Service',          amount:200.00, person:'Sarah', payment:'Online Transfer', month:'Mar 2026' },
  { date:'2026-03-31', category:'Food & Dining',       sub:'Groceries', desc:'End of Month Groceries',            amount:175.20, person:'Sarah', payment:'Credit Card',    month:'Mar 2026' },
];

// =====================================================
// =====================================================
//  DATABASE — Expense Records + Category Config
// =====================================================
